import { NextResponse } from "next/server";
import { recordSyncJobRun } from "@/lib/syncStatusStore";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const jobName = "monthly-inquiry-test";

function isAuthorized(request) {
  if (request.headers.get("x-vercel-cron") === "1") return true;
  if (/vercel-cron/i.test(request.headers.get("user-agent") || "")) return true;
  const secret = process.env.CRON_SECRET;
  if (!secret) return !process.env.VERCEL;
  const bearer = request.headers.get("authorization")?.replace(/^Bearer\s+/i, "");
  const headerSecret = request.headers.get("x-cron-secret");
  const querySecret = new URL(request.url).searchParams.get("secret");
  return [bearer, headerSecret, querySecret].includes(secret);
}

function siteUrlFromRequest(request) {
  const configured = process.env.SITE_URL || process.env.NEXT_PUBLIC_SITE_URL;
  if (configured) return configured.replace(/\/$/, "");
  const url = new URL(request.url);
  return `${url.protocol}//${url.host}`;
}

function timeoutSignal(ms) {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), ms);
  return {
    signal: controller.signal,
    clear: () => clearTimeout(timer)
  };
}

function testPayload() {
  const now = new Date().toISOString();
  return {
    name: "Cowinmagnet Monthly Form Test",
    email: "monthly-form-test@cowinmagnet.com",
    phone: "+1 555 0100",
    company: "Cowinmagnet Website Monitor",
    country: "System Test",
    buyerType: "Monthly email delivery test",
    productRequirement: "Form email delivery monitoring",
    applicationIndustry: "Website operations",
    materialType: "Not applicable",
    beltWidth: "Not applicable",
    installationPosition: "Not applicable",
    expectedQuantity: "1 automated test",
    sourcePath: "/api/cron/monthly-inquiry-test",
    sourceLanguage: "en",
    utm: "system=monthly-inquiry-test",
    consent: true,
    message: [
      "[AUTOMATED MONTHLY TEST - PLEASE IGNORE]",
      "",
      "This message was generated by the Cowinmagnet website on the 1st day of the month.",
      "Purpose: verify that the public inquiry form API and SMTP email delivery can send messages to the configured mailbox.",
      `Generated at: ${now}`
    ].join("\n"),
    attribution: {
      firstTouch: {
        source: "system",
        medium: "cron",
        campaign: "monthly-inquiry-test",
        platform: "cowinmagnet"
      },
      lastTouch: {
        source: "system",
        medium: "cron",
        campaign: "monthly-inquiry-test",
        platform: "cowinmagnet"
      },
      sessionTouch: {
        source: "system",
        medium: "cron",
        campaign: "monthly-inquiry-test",
        platform: "cowinmagnet"
      }
    }
  };
}

export async function GET(request) {
  if (!isAuthorized(request)) {
    return NextResponse.json({ ok: false, error: "Unauthorized" }, { status: 401 });
  }

  const startedAt = new Date();
  const targetUrl = `${siteUrlFromRequest(request)}/api/inquiry`;
  const timeout = timeoutSignal(30000);

  try {
    const response = await fetch(targetUrl, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "User-Agent": "Cowinmagnet-Monthly-Inquiry-Test/1.0"
      },
      body: JSON.stringify(testPayload()),
      signal: timeout.signal
    });
    const text = await response.text();
    const finishedAt = new Date();
    const ok = response.ok;

    await recordSyncJobRun({
      jobName,
      status: ok ? "success" : "failed",
      startedAt: startedAt.toISOString(),
      finishedAt: finishedAt.toISOString(),
      durationMs: finishedAt.getTime() - startedAt.getTime(),
      processedCount: ok ? 1 : 0,
      failedCount: ok ? 0 : 1,
      errorMessage: ok ? "" : `Inquiry API returned ${response.status}`,
      metadata: {
        targetUrl,
        statusCode: response.status,
        responseBody: text.slice(0, 500)
      }
    });

    return NextResponse.json({
      ok,
      status: ok ? "success" : "failed",
      statusCode: response.status,
      message: ok ? "Monthly inquiry test email sent." : "Monthly inquiry test failed.",
      response: text.slice(0, 500)
    }, { status: ok ? 200 : 502 });
  } catch (error) {
    const finishedAt = new Date();
    await recordSyncJobRun({
      jobName,
      status: "failed",
      startedAt: startedAt.toISOString(),
      finishedAt: finishedAt.toISOString(),
      durationMs: finishedAt.getTime() - startedAt.getTime(),
      failedCount: 1,
      errorMessage: error?.message || "Monthly inquiry test failed",
      metadata: { targetUrl }
    });

    return NextResponse.json(
      {
        ok: false,
        status: "failed",
        error: "Monthly inquiry test failed."
      },
      { status: 500 }
    );
  } finally {
    timeout.clear();
  }
}
