import type { Locale } from "@/lib/i18n";

// Shared customer-facing copy. Keep route slugs, product model numbers and form
// field values independent from these labels so language changes do not break URLs.
const copy = {
  en: {
    navigation: "Main navigation", openMenu: "Open navigation", closeMenu: "Close navigation", chooseLanguage: "Choose language",
    productCenter: "Product Center", categories: "Categories", popularProducts: "Popular Products",
    industries: "Industries", industrySolutions: "Industry Solutions",
    industryHeadline: "Industry Magnetic Separation Solutions",
    industryDescription: "Choose your industry to review problems, recommended equipment and application scenarios.",
    oem: "OEM/ODM", aboutUs: "About Us", support: "Support", contact: "Contact", search: "Search",
    home: "Home", privacy: "Privacy Policy", terms: "Terms of Use", catalog: "Product catalogue", allProducts: "All products", catalogHelp: "Need selection help?", catalogCount: "{start}–{end} of {total} products", previous: "Previous", next: "Next", page: "Page",
    footerHelp: "Need help selecting industrial equipment?", navigationLinks: "Navigation", contacts: "Contacts", mapLocation: "Company Location", mapTitle: "Find COWIN MAGNET in Quzhou, China", mapNote: "Use Google Maps for directions and satellite view.", mapOpen: "View on Google Maps",
    connect: "Connect", chatNow: "Chat now", globalB2b: "Global B2B", serviceFirst: "Service First",
    permanentSeries: "Permanent Magnet Series", electromagneticSeries: "Electromagnetic Series",
    rollersBars: "Magnetic Rollers & Magnetic Bars",
    name: "Name", yourName: "Your name", company: "Company Name", yourCompany: "Your company",
    email: "Email", country: "Country", countryHint: "Country / region", phone: "Phone / WhatsApp",
    industry: "Industry", material: "Material", beltWidth: "Belt Width", installation: "Installation Method",
    selectProduct: "Select Product Type", selectProductHint: "Select product type",
    project: "Tell us about your project", projectHint: "Material, capacity, installation position, or any other details.",
    selectedProduct: "Product selected", productInterest: "Product of interest", productInterestHint: "Product name or equipment type",
    requirements: "Product Requirement / Message", requirementsHint: "Tell us your material, belt width, capacity, installation height, and target iron removal result.",
    attachment: "Upload Drawing / Photo", attachmentHint: "Paste a file link or note that drawings/photos are available",
    submit: "Submit Inquiry", sending: "Sending...", success: "Thank you. Our sales team will contact you soon.",
    error: "The form could not be sent. Please email us directly and we will help you quickly.",
    suspendedMagnets: "Suspended Magnets", magneticPulleys: "Magnetic Pulleys", drumSeparators: "Drum Magnetic Separators",
    barsGrates: "Magnetic Bars & Grates", customizedSolution: "Customized Solution",
    homeSlogan: ["Metal", "out.", "Purity in."],
    homeProof: ["OEM/ODM for global buyers", "Reliable industrial solutions", "Focused on separation challenges", "Responsive support worldwide"],
    homeCategories: ["All Products", "Suspended Magnets", "Pulleys & Drums", "Magnetic Separators", "Components & Filters", "Metal Detection & Recycling", "Industrial Equipment", "Other Products", "Customized Solutions"],
    homeCards: [
      ["Suspended Permanent Magnet", "Captures tramp iron above a conveyor; periodic cleaning is required."],
      ["Magnetic Head Pulley", "Separates ferrous material at the conveyor discharge."],
      ["Dry Drum Separator", "Separates magnetic material in a dry processing line."],
      ["Magnetic Grid", "Traps ferrous fragments in hoppers and bins."],
      ["RCDB Electromagnetic Plate", "Suspended iron removal with a self-cooling electromagnetic unit."],
      ["Suspended Electromagnetic Separator", "Electromagnetic separation above a conveyor belt."]
    ],
    homeIndustries: ["Mining", "Recycling", "Cement", "Power Generation", "Aggregates", "Other Industries"],
    homeService: ["Service & Support", "From inquiry to operation, we're with you", "Technical consultation, customized design, manufacturing coordination, and after-sales support — all in one place.", "Contact Support"],
    videoCaption: "Reliable magnetic separation for real-world challenges", videoPlay: "Play COWIN MAGNET product showcase video", videoError: "The video could not start. Please try the play control again.", videoUnsupported: "Your browser does not support the video tag.",
    news: ["News", "Industry news and company insights", "Industry Updates", "Verified updates with source attribution and independent editorial context.", "All updates", "{start}–{end} of {total} news posts", "12 posts per page", "Read more", "Original articles are currently available in English."],
    searchUi: ["Search COWIN MAGNET", "Find products, industry solutions, news and technical guides.", "Search the website", "Search products, news, applications...", "Results", "{count} results for {query}", "Enter a keyword to search", "{start}–{end} of {total} results", "Open result", "No direct match found", "Try broader terms or contact us for selection support.", "Ask for selection support"],
    productTabs: ["Overview", "Selection", "Applications", "Technical data", "FAQ & quote"], productModel: "Model", openImage: "Open image", technicalNotice: "Published model references are shown here. Final technical values are confirmed from the selected configuration and site conditions.", productInstruction: "Share material, belt width, capacity and installation conditions for a configuration review.",
    productCategories: ["Suspended & Self-Unloading Iron Removers", "Magnetic Separation Equipment", "Metal Detection & Recycling Sorting", "Magnetic Components & Filters", "Industry Application Equipment"],
    featuredProducts: ["Suspended Permanent Magnetic Separator", "Suspended Electromagnetic Conveyor Belt Separator", "Round Electromagnetic Lifting Magnet", "Permanent Overband Magnetic Separator"],
    industryMenu: [["Recycling Industry", "Recover ferrous material and protect sorting equipment."], ["Mining Industry", "Protect crushers and support magnetic mineral recovery."], ["Cement & Aggregates", "Remove tramp iron from conveyors and process lines."], ["Food & Grain Processing", "Control ferrous contamination in dry and flowing materials."]]
  },
  es: {
    navigation: "Navegación principal", openMenu: "Abrir navegación", closeMenu: "Cerrar navegación", chooseLanguage: "Elegir idioma",
    productCenter: "Centro de productos", categories: "Categorías", popularProducts: "Productos populares",
    industries: "Industrias", industrySolutions: "Soluciones industriales",
    industryHeadline: "Soluciones de separación magnética por industria",
    industryDescription: "Elija su industria para ver los problemas, equipos recomendados y escenarios de aplicación.",
    oem: "OEM/ODM", aboutUs: "Quiénes somos", support: "Asistencia", contact: "Contacto", search: "Buscar",
    home: "Inicio", privacy: "Política de privacidad", terms: "Condiciones de uso", catalog: "Catálogo de productos", allProducts: "Todos los productos", catalogHelp: "¿Necesita ayuda para elegir?", catalogCount: "{start}–{end} de {total} productos", previous: "Anterior", next: "Siguiente", page: "Página",
    footerHelp: "¿Necesita ayuda para elegir equipos industriales?", navigationLinks: "Navegación", contacts: "Contactos", mapLocation: "Ubicación de la empresa", mapTitle: "Encuentre COWIN MAGNET en Quzhou, China", mapNote: "Use Google Maps para obtener indicaciones y ver el mapa satelital.", mapOpen: "Ver en Google Maps",
    connect: "Síganos", chatNow: "Chatear ahora", globalB2b: "B2B global", serviceFirst: "Servicio primero",
    permanentSeries: "Serie de imanes permanentes", electromagneticSeries: "Serie electromagnética",
    rollersBars: "Rodillos y barras magnéticas",
    name: "Nombre", yourName: "Su nombre", company: "Empresa", yourCompany: "Su empresa",
    email: "Correo electrónico", country: "País", countryHint: "País / región", phone: "Teléfono / WhatsApp",
    industry: "Industria", material: "Material", beltWidth: "Ancho de banda", installation: "Método de instalación",
    selectProduct: "Tipo de producto", selectProductHint: "Seleccione un tipo de producto",
    project: "Cuéntenos sobre su proyecto", projectHint: "Material, capacidad, posición de instalación u otros detalles.",
    selectedProduct: "Producto seleccionado", productInterest: "Producto de interés", productInterestHint: "Nombre o tipo de equipo",
    requirements: "Requisitos / mensaje", requirementsHint: "Indique material, ancho de banda, capacidad, altura de instalación y objetivo de eliminación de hierro.",
    attachment: "Plano / foto", attachmentHint: "Pegue un enlace o indique que dispone de planos o fotos",
    submit: "Enviar consulta", sending: "Enviando...", success: "Gracias. Nuestro equipo comercial se pondrá en contacto pronto.",
    error: "No se pudo enviar el formulario. Escríbanos directamente por correo electrónico.",
    suspendedMagnets: "Imanes suspendidos", magneticPulleys: "Poleas magnéticas", drumSeparators: "Separadores magnéticos de tambor",
    barsGrates: "Barras y rejillas magnéticas", customizedSolution: "Solución personalizada",
    homeSlogan: ["Fuera", "el metal.", "Más pureza."],
    homeProof: ["OEM/ODM para compradores globales", "Soluciones industriales fiables", "Atención a sus retos de separación", "Asistencia ágil en todo el mundo"],
    homeCategories: ["Todos los productos", "Imanes suspendidos", "Poleas y tambores", "Separadores magnéticos", "Componentes y filtros", "Detección y reciclaje", "Equipos industriales", "Otros productos", "Soluciones a medida"],
    homeCards: [
      ["Imán permanente suspendido", "Captura hierro contaminante sobre una cinta; requiere limpieza periódica."],
      ["Polea magnética de cabeza", "Separa materiales ferrosos en la descarga de la cinta."],
      ["Separador de tambor en seco", "Separa materiales magnéticos en una línea de proceso en seco."],
      ["Rejilla magnética", "Retiene fragmentos ferrosos en tolvas y depósitos."],
      ["Placa electromagnética RCDB", "Elimina hierro desde una posición suspendida con un electroimán autorrefrigerado."],
      ["Separador electromagnético suspendido", "Separación electromagnética sobre una cinta transportadora."]
    ],
    homeIndustries: ["Minería", "Reciclaje", "Cemento", "Generación eléctrica", "Áridos", "Otras industrias"],
    homeService: ["Servicio y asistencia", "Le acompañamos desde la consulta hasta la operación", "Asesoría técnica, diseño personalizado, coordinación de fabricación y asistencia posventa en un solo lugar.", "Contactar asistencia"],
    videoCaption: "Separación magnética fiable para desafíos reales", videoPlay: "Reproducir el video de COWIN MAGNET", videoError: "No se pudo iniciar el video. Intente reproducirlo de nuevo.", videoUnsupported: "Su navegador no admite videos.",
    news: ["Noticias", "Noticias del sector e información de la empresa", "Actualidad del sector", "Novedades verificadas con atribución de fuentes y contexto editorial independiente.", "Todas las noticias", "{start}–{end} de {total} noticias", "12 noticias por página", "Leer más", "Los artículos originales están disponibles por ahora en inglés."],
    searchUi: ["Buscar en COWIN MAGNET", "Encuentre productos, soluciones industriales, noticias y guías técnicas.", "Buscar en el sitio", "Buscar productos, noticias, aplicaciones...", "Resultados", "Resultados para {query}: {count}", "Escriba una palabra clave", "Mostrando {start}–{end} de {total}", "Abrir resultado", "No se encontró una coincidencia exacta", "Pruebe términos más generales o contáctenos para ayuda en la selección.", "Solicitar ayuda para elegir"],
    productTabs: ["Resumen", "Selección", "Aplicaciones", "Datos técnicos", "FAQ y cotización"], productModel: "Modelo", openImage: "Abrir imagen", technicalNotice: "Se muestran las referencias de modelo publicadas. Los valores técnicos finales se confirman según la configuración y las condiciones del sitio.", productInstruction: "Indique material, ancho de banda, capacidad y condiciones de instalación para revisar la configuración.",
    productCategories: ["Separadores suspendidos y autodescarga", "Equipos de separación magnética", "Detección de metales y clasificación para reciclaje", "Componentes y filtros magnéticos", "Equipos para aplicaciones industriales"],
    featuredProducts: ["Separador magnético permanente suspendido", "Separador electromagnético suspendido para cinta", "Electroimán circular de elevación", "Separador magnético permanente sobre cinta"],
    industryMenu: [["Reciclaje", "Recupere materiales ferrosos y proteja los equipos de clasificación."], ["Minería", "Proteja trituradoras y apoye la recuperación magnética de minerales."], ["Cemento y áridos", "Retire el hierro contaminante de cintas y líneas de proceso."], ["Alimentos y granos", "Controle la contaminación ferrosa en materiales secos y fluidos."]]
  },
  ru: {
    navigation: "Основная навигация", openMenu: "Открыть меню", closeMenu: "Закрыть меню", chooseLanguage: "Выбрать язык",
    productCenter: "Каталог продукции", categories: "Категории", popularProducts: "Популярные продукты",
    industries: "Отрасли", industrySolutions: "Отраслевые решения",
    industryHeadline: "Решения магнитной сепарации по отраслям",
    industryDescription: "Выберите отрасль, чтобы изучить задачи, рекомендуемое оборудование и сценарии применения.",
    oem: "OEM/ODM", aboutUs: "О нас", support: "Поддержка", contact: "Контакты", search: "Поиск",
    home: "Главная", privacy: "Политика конфиденциальности", terms: "Условия использования", catalog: "Каталог продукции", allProducts: "Все продукты", catalogHelp: "Нужна помощь в подборе?", catalogCount: "{start}–{end} из {total} продуктов", previous: "Назад", next: "Далее", page: "Страница",
    footerHelp: "Нужна помощь в подборе промышленного оборудования?", navigationLinks: "Навигация", contacts: "Контакты", mapLocation: "Адрес компании", mapTitle: "Найдите COWIN MAGNET в Цюйчжоу, Китай", mapNote: "Используйте Google Карты для маршрута и просмотра со спутника.", mapOpen: "Открыть в Google Картах",
    connect: "Связаться", chatNow: "Написать сейчас", globalB2b: "Международный B2B", serviceFirst: "Сервис прежде всего",
    permanentSeries: "Серия постоянных магнитов", electromagneticSeries: "Электромагнитная серия",
    rollersBars: "Магнитные ролики и стержни",
    name: "Имя", yourName: "Ваше имя", company: "Компания", yourCompany: "Ваша компания",
    email: "Эл. почта", country: "Страна", countryHint: "Страна / регион", phone: "Телефон / WhatsApp",
    industry: "Отрасль", material: "Материал", beltWidth: "Ширина ленты", installation: "Способ установки",
    selectProduct: "Тип продукта", selectProductHint: "Выберите тип продукта",
    project: "Расскажите о проекте", projectHint: "Материал, производительность, место установки и другие сведения.",
    selectedProduct: "Выбранный продукт", productInterest: "Интересующий продукт", productInterestHint: "Название или тип оборудования",
    requirements: "Требования / сообщение", requirementsHint: "Укажите материал, ширину ленты, производительность, высоту установки и цель удаления железа.",
    attachment: "Чертеж / фото", attachmentHint: "Вставьте ссылку или сообщите о наличии чертежей и фото",
    submit: "Отправить запрос", sending: "Отправка...", success: "Спасибо. Наш отдел продаж скоро свяжется с вами.",
    error: "Не удалось отправить форму. Напишите нам напрямую по электронной почте.",
    suspendedMagnets: "Подвесные магниты", magneticPulleys: "Магнитные шкивы", drumSeparators: "Барабанные магнитные сепараторы",
    barsGrates: "Магнитные стержни и решетки", customizedSolution: "Индивидуальное решение",
    homeSlogan: ["Металл", "удален.", "Чистота выше."],
    homeProof: ["OEM/ODM для международных покупателей", "Надежные промышленные решения", "Внимание к задачам сепарации", "Оперативная поддержка по всему миру"],
    homeCategories: ["Все продукты", "Подвесные магниты", "Шкивы и барабаны", "Магнитные сепараторы", "Компоненты и фильтры", "Детекция и переработка", "Промышленное оборудование", "Другие продукты", "Индивидуальные решения"],
    homeCards: [
      ["Подвесной постоянный магнит", "Улавливает железные включения над конвейером; требует периодической очистки."],
      ["Головной магнитный барабан", "Отделяет железные материалы на выходе конвейера."],
      ["Барабанный сепаратор сухого типа", "Отделяет магнитный материал на сухой технологической линии."],
      ["Магнитная решётка", "Задерживает железные фрагменты в бункерах и ёмкостях."],
      ["Электромагнитная плита RCDB", "Удаляет железо в подвесном положении с самоохлаждающимся электромагнитом."],
      ["Подвесной электромагнитный сепаратор", "Электромагнитная сепарация над конвейерной лентой."]
    ],
    homeIndustries: ["Горнодобывающая отрасль", "Переработка", "Цемент", "Энергетика", "Нерудные материалы", "Другие отрасли"],
    homeService: ["Сервис и поддержка", "От запроса до запуска — мы рядом", "Техническая консультация, индивидуальный подбор, координация производства и послепродажная поддержка.", "Связаться с поддержкой"],
    videoCaption: "Надежная магнитная сепарация для практических задач", videoPlay: "Воспроизвести видео COWIN MAGNET", videoError: "Видео не запустилось. Попробуйте воспроизвести его снова.", videoUnsupported: "Ваш браузер не поддерживает видео.",
    news: ["Новости", "Новости отрасли и компании", "Отраслевые новости", "Проверенные материалы с указанием источников и независимым редакционным контекстом.", "Все новости", "{start}–{end} из {total} новостей", "12 новостей на странице", "Подробнее", "Оригиналы статей пока доступны на английском языке."],
    searchUi: ["Поиск по COWIN MAGNET", "Найдите продукцию, отраслевые решения, новости и технические руководства.", "Поиск по сайту", "Поиск продуктов, новостей, применений...", "Результаты", "По запросу {query}: {count}", "Введите ключевое слово", "Показаны {start}–{end} из {total}", "Открыть результат", "Точных совпадений не найдено", "Попробуйте более общие слова или обратитесь за помощью в подборе.", "Запросить помощь в подборе"],
    productTabs: ["Обзор", "Подбор", "Применение", "Технические данные", "Вопросы и запрос"], productModel: "Модель", openImage: "Открыть изображение", technicalNotice: "Здесь указаны опубликованные обозначения моделей. Итоговые технические значения подтверждаются для выбранной конфигурации и условий объекта.", productInstruction: "Сообщите материал, ширину ленты, производительность и условия установки для рассмотрения конфигурации.",
    productCategories: ["Подвесные и саморазгружающиеся железоотделители", "Оборудование магнитной сепарации", "Металлодетекция и сортировка для переработки", "Магнитные компоненты и фильтры", "Оборудование для промышленных применений"],
    featuredProducts: ["Подвесной постоянный магнитный сепаратор", "Подвесной электромагнитный сепаратор для конвейера", "Круглый подъемный электромагнит", "Постоянный надленточный магнитный сепаратор"],
    industryMenu: [["Переработка", "Извлечение железных материалов и защита сортировочного оборудования."], ["Горнодобывающая отрасль", "Защита дробилок и магнитное извлечение минералов."], ["Цемент и нерудные материалы", "Удаление железных включений с конвейеров и технологических линий."], ["Пищевая промышленность и зерно", "Контроль железных примесей в сухих и сыпучих материалах."]]
  },
  ar: {
    navigation: "التنقل الرئيسي", openMenu: "فتح القائمة", closeMenu: "إغلاق القائمة", chooseLanguage: "اختر اللغة",
    productCenter: "مركز المنتجات", categories: "الفئات", popularProducts: "المنتجات الشائعة",
    industries: "القطاعات", industrySolutions: "حلول القطاعات",
    industryHeadline: "حلول الفصل المغناطيسي حسب القطاع",
    industryDescription: "اختر القطاع للاطلاع على التحديات والمعدات الموصى بها وسيناريوهات التطبيق.",
    oem: "OEM/ODM", aboutUs: "من نحن", support: "الدعم", contact: "اتصل بنا", search: "بحث",
    home: "الرئيسية", privacy: "سياسة الخصوصية", terms: "شروط الاستخدام", catalog: "كتالوج المنتجات", allProducts: "كل المنتجات", catalogHelp: "هل تحتاج مساعدة في الاختيار؟", catalogCount: "{start}–{end} من {total} منتجًا", previous: "السابق", next: "التالي", page: "صفحة",
    footerHelp: "هل تحتاج مساعدة في اختيار المعدات الصناعية؟", navigationLinks: "التنقل", contacts: "التواصل", mapLocation: "موقع الشركة", mapTitle: "اعثر على COWIN MAGNET في تشوتشو، الصين", mapNote: "استخدم خرائط Google لمعرفة الطريق وعرض القمر الصناعي.", mapOpen: "عرض على خرائط Google",
    connect: "تابعنا", chatNow: "تحدث الآن", globalB2b: "تجارة دولية B2B", serviceFirst: "الخدمة أولاً",
    permanentSeries: "سلسلة المغناطيس الدائم", electromagneticSeries: "السلسلة الكهرومغناطيسية",
    rollersBars: "البكرات والقضبان المغناطيسية",
    name: "الاسم", yourName: "اسمك", company: "اسم الشركة", yourCompany: "شركتك",
    email: "البريد الإلكتروني", country: "الدولة", countryHint: "الدولة / المنطقة", phone: "الهاتف / WhatsApp",
    industry: "القطاع", material: "المادة", beltWidth: "عرض السير", installation: "طريقة التركيب",
    selectProduct: "نوع المنتج", selectProductHint: "اختر نوع المنتج",
    project: "أخبرنا عن مشروعك", projectHint: "المادة والسعة وموقع التركيب وأي تفاصيل أخرى.",
    selectedProduct: "المنتج المحدد", productInterest: "المنتج المطلوب", productInterestHint: "اسم المنتج أو نوع المعدات",
    requirements: "المتطلبات / الرسالة", requirementsHint: "أخبرنا بالمادة وعرض السير والسعة وارتفاع التركيب وهدف إزالة الحديد.",
    attachment: "مخطط / صورة", attachmentHint: "ألصق رابط الملف أو اذكر توفر المخططات والصور",
    submit: "إرسال الاستفسار", sending: "جارٍ الإرسال...", success: "شكرًا لك. سيتواصل معك فريق المبيعات قريبًا.",
    error: "تعذر إرسال النموذج. يرجى مراسلتنا مباشرة عبر البريد الإلكتروني.",
    suspendedMagnets: "مغناطيسات معلقة", magneticPulleys: "بكرات مغناطيسية", drumSeparators: "فواصل مغناطيسية أسطوانية",
    barsGrates: "قضبان وشبكات مغناطيسية", customizedSolution: "حل مخصص",
    homeSlogan: ["إزالة", "المعادن.", "نقاء أعلى."],
    homeProof: ["خدمات OEM/ODM للمشترين حول العالم", "حلول صناعية موثوقة", "نهتم بتحديات الفصل لديك", "دعم سريع في مختلف أنحاء العالم"],
    homeCategories: ["كل المنتجات", "مغناطيسات معلقة", "بكرات وأسطوانات", "فواصل مغناطيسية", "مكونات ومرشحات", "كشف المعادن وإعادة التدوير", "معدات صناعية", "منتجات أخرى", "حلول مخصصة"],
    homeCards: [
      ["مغناطيس دائم معلّق", "يلتقط الحديد الدخيل فوق السير؛ ويتطلب تنظيفًا دوريًا."],
      ["بكرة رأس مغناطيسية", "تفصل المواد الحديدية عند مخرج السير الناقل."],
      ["فاصل أسطواني جاف", "يفصل المواد المغناطيسية في خط معالجة جاف."],
      ["شبكة مغناطيسية", "تحتجز الشظايا الحديدية في القواديس والحاويات."],
      ["لوحة كهرومغناطيسية RCDB", "تزيل الحديد من موضع معلّق بوحدة كهرومغناطيسية ذاتية التبريد."],
      ["فاصل كهرومغناطيسي معلّق", "فصل كهرومغناطيسي فوق سير ناقل."]
    ],
    homeIndustries: ["التعدين", "إعادة التدوير", "الأسمنت", "توليد الطاقة", "الركام", "قطاعات أخرى"],
    homeService: ["الخدمة والدعم", "نرافقك من الاستفسار حتى التشغيل", "استشارة فنية وتصميم مخصص وتنسيق التصنيع ودعم ما بعد البيع في مكان واحد.", "تواصل مع الدعم"],
    videoCaption: "فصل مغناطيسي موثوق لتحديات التشغيل الفعلية", videoPlay: "تشغيل فيديو COWIN MAGNET", videoError: "تعذر تشغيل الفيديو. حاول الضغط على زر التشغيل مرة أخرى.", videoUnsupported: "متصفحك لا يدعم تشغيل الفيديو.",
    news: ["الأخبار", "أخبار القطاع وتحديثات الشركة", "تحديثات القطاع", "تحديثات موثقة مع ذكر المصادر وسياق تحريري مستقل.", "جميع الأخبار", "{start}–{end} من {total} خبرًا", "12 خبرًا في الصفحة", "اقرأ المزيد", "المقالات الأصلية متاحة حاليًا باللغة الإنجليزية."],
    searchUi: ["البحث في COWIN MAGNET", "اعثر على المنتجات والحلول الصناعية والأخبار والأدلة الفنية.", "البحث في الموقع", "ابحث عن منتجات أو أخبار أو تطبيقات...", "النتائج", "نتائج البحث عن {query}: {count}", "أدخل كلمة مفتاحية للبحث", "المعروض {start}–{end} من أصل {total}", "فتح النتيجة", "لم يُعثر على تطابق مباشر", "جرّب كلمات أعم أو تواصل معنا للمساعدة في الاختيار.", "اطلب المساعدة في الاختيار"],
    productTabs: ["نظرة عامة", "الاختيار", "التطبيقات", "البيانات الفنية", "الأسئلة وعرض السعر"], productModel: "الطراز", openImage: "فتح الصورة", technicalNotice: "تُعرض رموز الطرازات المنشورة هنا. تُؤكَّد القيم الفنية النهائية حسب التكوين المختار وظروف الموقع.", productInstruction: "أرسل نوع المادة وعرض السير والسعة وظروف التركيب لمراجعة التكوين.",
    productCategories: ["مزيلات حديد معلقة وذاتية التفريغ", "معدات الفصل المغناطيسي", "كشف المعادن وفرز إعادة التدوير", "مكونات ومرشحات مغناطيسية", "معدات التطبيقات الصناعية"],
    featuredProducts: ["فاصل مغناطيسي دائم معلق", "فاصل كهرومغناطيسي معلق للسير الناقل", "مغناطيس رفع كهرومغناطيسي دائري", "فاصل مغناطيسي دائم فوق السير"],
    industryMenu: [["إعادة التدوير", "استرجاع المواد الحديدية وحماية معدات الفرز."], ["التعدين", "حماية الكسارات ودعم استرجاع المعادن مغناطيسيًا."], ["الأسمنت والركام", "إزالة الحديد من السيور وخطوط المعالجة."], ["الأغذية والحبوب", "التحكم في التلوث الحديدي في المواد الجافة والمتدفقة."]]
  },
  fr: {
    navigation: "Navigation principale", openMenu: "Ouvrir le menu", closeMenu: "Fermer le menu", chooseLanguage: "Choisir la langue",
    productCenter: "Centre produits", categories: "Catégories", popularProducts: "Produits populaires",
    industries: "Industries", industrySolutions: "Solutions par industrie",
    industryHeadline: "Solutions de séparation magnétique par industrie",
    industryDescription: "Choisissez votre industrie pour découvrir les besoins, les équipements recommandés et les applications.",
    oem: "OEM/ODM", aboutUs: "À propos", support: "Assistance", contact: "Contact", search: "Rechercher",
    home: "Accueil", privacy: "Politique de confidentialité", terms: "Conditions d'utilisation", catalog: "Catalogue produits", allProducts: "Tous les produits", catalogHelp: "Besoin d'aide pour choisir ?", catalogCount: "{start}–{end} sur {total} produits", previous: "Précédent", next: "Suivant", page: "Page",
    footerHelp: "Besoin d'aide pour choisir votre équipement industriel ?", navigationLinks: "Navigation", contacts: "Contacts", mapLocation: "Adresse de l'entreprise", mapTitle: "Retrouvez COWIN MAGNET à Quzhou, en Chine", mapNote: "Utilisez Google Maps pour l'itinéraire et la vue satellite.", mapOpen: "Voir sur Google Maps",
    connect: "Suivez-nous", chatNow: "Discuter maintenant", globalB2b: "B2B mondial", serviceFirst: "Service avant tout",
    permanentSeries: "Série à aimants permanents", electromagneticSeries: "Série électromagnétique",
    rollersBars: "Rouleaux et barres magnétiques",
    name: "Nom", yourName: "Votre nom", company: "Entreprise", yourCompany: "Votre entreprise",
    email: "E-mail", country: "Pays", countryHint: "Pays / région", phone: "Téléphone / WhatsApp",
    industry: "Industrie", material: "Matériau", beltWidth: "Largeur de bande", installation: "Méthode d'installation",
    selectProduct: "Type de produit", selectProductHint: "Sélectionnez un type de produit",
    project: "Parlez-nous de votre projet", projectHint: "Matériau, capacité, emplacement d'installation et autres détails.",
    selectedProduct: "Produit sélectionné", productInterest: "Produit recherché", productInterestHint: "Nom du produit ou type d'équipement",
    requirements: "Exigences / message", requirementsHint: "Indiquez le matériau, la largeur de bande, la capacité, la hauteur d'installation et l'objectif d'élimination du fer.",
    attachment: "Plan / photo", attachmentHint: "Collez un lien ou indiquez la disponibilité de plans ou de photos",
    submit: "Envoyer la demande", sending: "Envoi en cours...", success: "Merci. Notre équipe commerciale vous contactera bientôt.",
    error: "Le formulaire n'a pas pu être envoyé. Contactez-nous directement par e-mail.",
    suspendedMagnets: "Aimants suspendus", magneticPulleys: "Poulies magnétiques", drumSeparators: "Séparateurs magnétiques à tambour",
    barsGrates: "Barres et grilles magnétiques", customizedSolution: "Solution sur mesure",
    homeSlogan: ["Métaux", "retirés.", "Pureté accrue."],
    homeProof: ["OEM/ODM pour acheteurs internationaux", "Solutions industrielles fiables", "Vos défis de séparation au cœur du projet", "Assistance réactive dans le monde entier"],
    homeCategories: ["Tous les produits", "Aimants suspendus", "Poulies et tambours", "Séparateurs magnétiques", "Composants et filtres", "Détection et recyclage", "Équipements industriels", "Autres produits", "Solutions sur mesure"],
    homeCards: [
      ["Aimant permanent suspendu", "Capte les morceaux de fer au-dessus d'un convoyeur ; nécessite un nettoyage périodique."],
      ["Poulie magnétique de tête", "Sépare les matières ferreuses à la sortie du convoyeur."],
      ["Séparateur à tambour sec", "Sépare les matières magnétiques sur une ligne de traitement à sec."],
      ["Grille magnétique", "Retient les fragments ferreux dans les trémies et les bacs."],
      ["Plaque électromagnétique RCDB", "Retire le fer en position suspendue avec un électroaimant à refroidissement autonome."],
      ["Séparateur électromagnétique suspendu", "Séparation électromagnétique au-dessus d'une bande transporteuse."]
    ],
    homeIndustries: ["Mines", "Recyclage", "Ciment", "Production d'énergie", "Granulats", "Autres industries"],
    homeService: ["Service et assistance", "De la demande à l'exploitation, nous restons à vos côtés", "Conseil technique, conception personnalisée, coordination de fabrication et assistance après-vente réunis.", "Contacter l'assistance"],
    videoCaption: "Une séparation magnétique fiable pour les défis du terrain", videoPlay: "Lire la vidéo COWIN MAGNET", videoError: "La vidéo n'a pas pu démarrer. Réessayez avec le bouton de lecture.", videoUnsupported: "Votre navigateur ne prend pas en charge la vidéo.",
    news: ["Actualités", "Actualités du secteur et de l'entreprise", "Actualités du secteur", "Informations vérifiées avec attribution des sources et contexte éditorial indépendant.", "Toutes les actualités", "{start}–{end} sur {total} actualités", "12 actualités par page", "Lire la suite", "Les articles originaux sont actuellement disponibles en anglais."],
    searchUi: ["Rechercher sur COWIN MAGNET", "Trouvez produits, solutions industrielles, actualités et guides techniques.", "Rechercher sur le site", "Rechercher produits, actualités, applications...", "Résultats", "Résultats pour {query} : {count}", "Saisissez un mot-clé", "Affichage de {start}–{end} sur {total}", "Ouvrir le résultat", "Aucune correspondance directe", "Essayez des termes plus généraux ou contactez-nous pour être conseillé.", "Demander de l'aide pour choisir"],
    productTabs: ["Présentation", "Sélection", "Applications", "Données techniques", "FAQ et devis"], productModel: "Modèle", openImage: "Ouvrir l'image", technicalNotice: "Les références de modèles publiées figurent ici. Les valeurs techniques finales sont confirmées selon la configuration choisie et les conditions du site.", productInstruction: "Indiquez le matériau, la largeur de bande, le débit et les conditions d'installation pour étudier la configuration.",
    productCategories: ["Séparateurs suspendus et autonettoyants", "Équipements de séparation magnétique", "Détection des métaux et tri pour le recyclage", "Composants et filtres magnétiques", "Équipements pour applications industrielles"],
    featuredProducts: ["Séparateur magnétique permanent suspendu", "Séparateur électromagnétique suspendu pour convoyeur", "Électroaimant de levage circulaire", "Séparateur magnétique permanent au-dessus de la bande"],
    industryMenu: [["Recyclage", "Récupérez les métaux ferreux et protégez les équipements de tri."], ["Mines", "Protégez les concasseurs et facilitez la récupération magnétique des minéraux."], ["Ciment et granulats", "Retirez le fer indésirable des convoyeurs et des lignes de traitement."], ["Agroalimentaire et céréales", "Maîtrisez la contamination ferreuse des matériaux secs et en écoulement."]]
  },
  pt: {
    navigation: "Navegação principal", openMenu: "Abrir menu", closeMenu: "Fechar menu", chooseLanguage: "Escolher idioma",
    productCenter: "Centro de produtos", categories: "Categorias", popularProducts: "Produtos populares",
    industries: "Indústrias", industrySolutions: "Soluções por indústria",
    industryHeadline: "Soluções de separação magnética por indústria",
    industryDescription: "Escolha sua indústria para ver desafios, equipamentos recomendados e aplicações.",
    oem: "OEM/ODM", aboutUs: "Sobre nós", support: "Suporte", contact: "Contato", search: "Buscar",
    home: "Início", privacy: "Política de privacidade", terms: "Termos de uso", catalog: "Catálogo de produtos", allProducts: "Todos os produtos", catalogHelp: "Precisa de ajuda para escolher?", catalogCount: "{start}–{end} de {total} produtos", previous: "Anterior", next: "Próximo", page: "Página",
    footerHelp: "Precisa de ajuda para escolher equipamentos industriais?", navigationLinks: "Navegação", contacts: "Contatos", mapLocation: "Localização da empresa", mapTitle: "Encontre a COWIN MAGNET em Quzhou, China", mapNote: "Use o Google Maps para rotas e visualização por satélite.", mapOpen: "Ver no Google Maps",
    connect: "Conecte-se", chatNow: "Converse agora", globalB2b: "B2B global", serviceFirst: "Serviço em primeiro lugar",
    permanentSeries: "Série de ímãs permanentes", electromagneticSeries: "Série eletromagnética",
    rollersBars: "Rolos e barras magnéticas",
    name: "Nome", yourName: "Seu nome", company: "Empresa", yourCompany: "Sua empresa",
    email: "E-mail", country: "País", countryHint: "País / região", phone: "Telefone / WhatsApp",
    industry: "Indústria", material: "Material", beltWidth: "Largura da correia", installation: "Método de instalação",
    selectProduct: "Tipo de produto", selectProductHint: "Selecione um tipo de produto",
    project: "Conte-nos sobre seu projeto", projectHint: "Material, capacidade, posição de instalação e outros detalhes.",
    selectedProduct: "Produto selecionado", productInterest: "Produto de interesse", productInterestHint: "Nome ou tipo de equipamento",
    requirements: "Requisitos / mensagem", requirementsHint: "Informe material, largura da correia, capacidade, altura de instalação e objetivo de remoção de ferro.",
    attachment: "Desenho / foto", attachmentHint: "Cole um link ou informe que há desenhos ou fotos disponíveis",
    submit: "Enviar consulta", sending: "Enviando...", success: "Obrigado. Nossa equipe comercial entrará em contato em breve.",
    error: "Não foi possível enviar o formulário. Entre em contato diretamente por e-mail.",
    suspendedMagnets: "Ímãs suspensos", magneticPulleys: "Polias magnéticas", drumSeparators: "Separadores magnéticos de tambor",
    barsGrates: "Barras e grades magnéticas", customizedSolution: "Solução personalizada",
    homeSlogan: ["Metal", "removido.", "Mais pureza."],
    homeProof: ["OEM/ODM para compradores globais", "Soluções industriais confiáveis", "Foco nos seus desafios de separação", "Suporte ágil em todo o mundo"],
    homeCategories: ["Todos os produtos", "Ímãs suspensos", "Polias e tambores", "Separadores magnéticos", "Componentes e filtros", "Detecção e reciclagem", "Equipamentos industriais", "Outros produtos", "Soluções personalizadas"],
    homeCards: [
      ["Ímã permanente suspenso", "Captura ferro contaminante acima da correia; requer limpeza periódica."],
      ["Polia magnética de cabeça", "Separa materiais ferrosos na descarga do transportador."],
      ["Separador de tambor a seco", "Separa material magnético numa linha de processamento a seco."],
      ["Grade magnética", "Retém fragmentos ferrosos em tremonhas e depósitos."],
      ["Placa eletromagnética RCDB", "Remove ferro em posição suspensa com uma unidade eletromagnética de autorrefrigeração."],
      ["Separador eletromagnético suspenso", "Separação eletromagnética acima de uma correia transportadora."]
    ],
    homeIndustries: ["Mineração", "Reciclagem", "Cimento", "Geração de energia", "Agregados", "Outras indústrias"],
    homeService: ["Serviço e suporte", "Da consulta à operação, estamos com você", "Consultoria técnica, projeto personalizado, coordenação de fabricação e suporte pós-venda em um só lugar.", "Contatar suporte"],
    videoCaption: "Separação magnética confiável para desafios reais", videoPlay: "Reproduzir o vídeo da COWIN MAGNET", videoError: "Não foi possível iniciar o vídeo. Tente reproduzi-lo novamente.", videoUnsupported: "Seu navegador não oferece suporte a vídeos.",
    news: ["Notícias", "Notícias do setor e da empresa", "Atualizações do setor", "Atualizações verificadas com indicação das fontes e contexto editorial independente.", "Todas as notícias", "{start}–{end} de {total} notícias", "12 notícias por página", "Leia mais", "Os artigos originais estão disponíveis por enquanto em inglês."],
    searchUi: ["Buscar na COWIN MAGNET", "Encontre produtos, soluções industriais, notícias e guias técnicos.", "Buscar no site", "Buscar produtos, notícias, aplicações...", "Resultados", "Resultados para {query}: {count}", "Digite uma palavra-chave", "Exibindo {start}–{end} de {total}", "Abrir resultado", "Nenhuma correspondência direta", "Tente termos mais amplos ou entre em contato para obter ajuda na seleção.", "Solicitar ajuda na seleção"],
    productTabs: ["Visão geral", "Seleção", "Aplicações", "Dados técnicos", "Perguntas e cotação"], productModel: "Modelo", openImage: "Abrir imagem", technicalNotice: "As referências de modelo publicadas são mostradas aqui. Os valores técnicos finais são confirmados conforme a configuração escolhida e as condições do local.", productInstruction: "Informe material, largura da correia, capacidade e condições de instalação para avaliar a configuração.",
    productCategories: ["Removedores de ferro suspensos e autolimpantes", "Equipamentos de separação magnética", "Detecção de metais e classificação para reciclagem", "Componentes e filtros magnéticos", "Equipamentos para aplicações industriais"],
    featuredProducts: ["Separador magnético permanente suspenso", "Separador eletromagnético suspenso para correia", "Eletroímã circular de elevação", "Separador magnético permanente sobre a correia"],
    industryMenu: [["Reciclagem", "Recupere materiais ferrosos e proteja os equipamentos de classificação."], ["Mineração", "Proteja britadores e apoie a recuperação magnética de minerais."], ["Cimento e agregados", "Remova ferro indesejado das correias e linhas de processo."], ["Alimentos e grãos", "Controle a contaminação ferrosa em materiais secos e em fluxo."]]
  }
} as const;

export function getPublicUi(locale: Locale) {
  return copy[locale];
}
